// examples/next-app/app/page.tsx
'use client';

import { useState } from 'react';

export default function Page() {
  const [count, setCount] = useState(0);
  const [todos, setTodos] = useState<string[]>([]);
  const [draft, setDraft] = useState('');

  function addTodo(e: React.FormEvent) {
    e.preventDefault();
    const text = draft.trim();
    if (!text) return;
    setTodos(prev => [...prev, text]);
    setDraft('');
  }

  return (
    <main>
      <h1>Hover · Next example</h1>
      <p>
        Smoke target for <code>@hover-dev/next</code>. Service starts via
        <code> instrumentation.ts</code>; widget injects via
        <code> &lt;HoverScript /&gt; </code> in <code>app/layout.tsx</code>.
      </p>

      <section style={{ marginTop: '2rem', paddingTop: '1rem', borderTop: '1px solid #eee' }}>
        <h2>Counter</h2>
        <p>
          Count: <span>{count}</span>
        </p>
        <button style={{ padding: '0.4rem 0.8rem', marginRight: '0.5rem' }} onClick={() => setCount(c => c + 1)}>
          +1
        </button>
        <button style={{ padding: '0.4rem 0.8rem' }} onClick={() => setCount(0)}>
          Reset
        </button>
      </section>

      <section style={{ marginTop: '2rem', paddingTop: '1rem', borderTop: '1px solid #eee' }}>
        <h2>Todos</h2>
        <form onSubmit={addTodo}>
          <input
            value={draft}
            onChange={e => setDraft(e.target.value)}
            placeholder="What needs doing?"
            style={{ padding: '0.4rem', marginRight: '0.5rem' }}
          />
          <button type="submit" style={{ padding: '0.4rem 0.8rem' }}>
            Add
          </button>
        </form>
        <ul>
          {todos.map((t, i) => (
            <li key={i} style={{ margin: '0.2rem 0' }}>
              {t}
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}

// examples/nuxt-app/app.vue
<script setup lang="ts">
// Plain Vue 3 composition — no router, no pages/ directory needed. The
// agent's job here is to drive these controls; the page exists to give
// it a stable smoke target with a counter + todo list.
const count = ref(0);
const todos = ref<string[]>([]);
const draft = ref('');
function addTodo() {
  const text = draft.value.trim();
  if (!text) return;
  todos.value.push(text);
  draft.value = '';
}
</script>

<template>
  <main>
    <h1>Hover · Nuxt example</h1>
    <p>
      This is the Nuxt smoke target. Nuxt renders through Nitro, so the
      <code>vite-plugin-hover</code> path doesn't fully work here — the
      <code>@hover-dev/nuxt</code> module bridges via Nuxt's
      <code>app.head.script</code>.
    </p>

    <section>
      <h2>Counter</h2>
      <p>Count: <span>{{ count }}</span></p>
      <button @click="count++">+1</button>
      <button @click="count = 0">Reset</button>
    </section>

    <section>
      <h2>Todos</h2>
      <form @submit.prevent="addTodo">
        <input v-model="draft" type="text" placeholder="What needs doing?" />
        <button type="submit">Add</button>
      </form>
      <ul>
        <li v-for="(t, i) in todos" :key="i">{{ t }}</li>
      </ul>
    </section>
  </main>
</template>

<style>
body { font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; padding: 0 1rem; }
h1 { margin-bottom: 0.5rem; }
section { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; }
button { padding: 0.4rem 0.8rem; margin-right: 0.5rem; }
input { padding: 0.4rem; margin-right: 0.5rem; }
code { background: #f3f3f3; padding: 0.1rem 0.3rem; border-radius: 3px; }
li { margin: 0.2rem 0; }
</style>
